# Generated by Django 4.2 on 2026-05-11 18:30

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_number', models.CharField(max_length=20, unique=True, verbose_name='Numéro de devis')),
                ('date', models.DateField(default=datetime.datetime.now, verbose_name='Date du devis')),
                ('validity_date', models.DateField(verbose_name='Date de validité')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('sent', 'Envoyé'), ('accepted', 'Accepté'), ('rejected', 'Rejeté'), ('expired', 'Expiré'), ('converted', 'Converti en facture')], default='draft', max_length=20, verbose_name='Statut')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Sous-total')),
                ('remise_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Remise %')),
                ('remise_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Montant remise')),
                ('rabais_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Rabais %')),
                ('rabais_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Montant rabais')),
                ('escompte_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Escompte %')),
                ('escompte_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Montant escompte')),
                ('total_discount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Réduction totale')),
                ('tva_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Montant TVA')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total')),
                ('terms_conditions', models.TextField(blank=True, null=True, verbose_name='Conditions générales')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='invoice_app.client', verbose_name='Client')),
                ('converted_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_source', to='invoice_app.invoice', verbose_name='Facture générée')),
            ],
            options={
                'verbose_name': 'Devis',
                'verbose_name_plural': 'Devis',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='QuoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantité')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix unitaire')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoice_app.product', verbose_name='Produit')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoice_app.quote', verbose_name='Devis')),
            ],
            options={
                'verbose_name': 'Ligne de devis',
                'verbose_name_plural': 'Lignes de devis',
            },
        ),
    ]
