# Generated by Django 4.2 on 2026-05-11 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0002_quote_quoteitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_type', models.CharField(choices=[('invoice_created', 'Facture créée'), ('invoice_sent', 'Facture envoyée'), ('invoice_reminder', 'Rappel facture'), ('quote_sent', 'Devis envoyé'), ('quote_accepted', 'Confirmation acceptation devis'), ('payment_thank_you', 'Remerciement paiement')], max_length=50, unique=True, verbose_name='Type de template')),
                ('subject', models.CharField(max_length=255, verbose_name='Sujet')),
                ('body', models.TextField(verbose_name='Contenu du email (HTML)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Template Email',
                'verbose_name_plural': 'Templates Email',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('invoice_created', 'Facture créée'), ('invoice_sent', 'Facture envoyée'), ('invoice_paid', 'Facture payée'), ('invoice_overdue', 'Facture en retard'), ('quote_created', 'Devis créé'), ('quote_accepted', 'Devis accepté'), ('quote_rejected', 'Devis rejeté'), ('payment_received', 'Paiement reçu'), ('reminder', 'Rappel')], max_length=50, verbose_name='Type')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('sent', 'Envoyé'), ('failed', 'Échoué'), ('read', 'Lu')], default='pending', max_length=20, verbose_name='Statut')),
                ('subject', models.CharField(max_length=255, verbose_name='Sujet')),
                ('message', models.TextField(verbose_name='Message')),
                ('recipient_email', models.EmailField(max_length=254, verbose_name='Email du destinataire')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name="Date d'envoi")),
                ('error_message', models.TextField(blank=True, null=True, verbose_name="Message d'erreur")),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='invoice_app.client', verbose_name='Client')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='invoice_app.invoice', verbose_name='Facture')),
                ('quote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='invoice_app.quote', verbose_name='Devis')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['client', '-created_at'], name='invoice_app_client__901700_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['status', 'type'], name='invoice_app_status_e13d0e_idx'),
        ),
    ]
