# Generated by Django 4.2 on 2026-05-11 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0003_emailtemplate_notification_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Créé'), ('update', 'Modifié'), ('delete', 'Supprimé'), ('view', 'Consulté')], max_length=20, verbose_name='Action')),
                ('model', models.CharField(choices=[('Client', 'Client'), ('Product', 'Produit'), ('Invoice', 'Facture'), ('InvoiceItem', 'Ligne Facture'), ('Payment', 'Paiement'), ('Quote', 'Devis'), ('QuoteItem', 'Ligne Devis'), ('CompanyInfo', 'Info Entreprise'), ('Notification', 'Notification'), ('EmailTemplate', 'Template Email')], max_length=50, verbose_name='Modèle')),
                ('object_id', models.IntegerField(verbose_name="ID de l'objet")),
                ('object_str', models.CharField(blank=True, max_length=255, null=True, verbose_name='Objet (str)')),
                ('user', models.CharField(blank=True, max_length=255, null=True, verbose_name='Utilisateur')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('old_values', models.JSONField(blank=True, default=dict, verbose_name='Anciennes valeurs')),
                ('new_values', models.JSONField(blank=True, default=dict, verbose_name='Nouvelles valeurs')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Date/Heure')),
            ],
            options={
                'verbose_name': "Journal d'audit",
                'verbose_name_plural': "Journaux d'audit",
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['model', 'object_id'], name='invoice_app_model_650d25_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['-timestamp'], name='invoice_app_timesta_8b5aec_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action'], name='invoice_app_action_5c934f_idx'),
        ),
    ]
