# Generated by Django 4.2 on 2026-05-12 20:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0004_auditlog_auditlog_invoice_app_model_650d25_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingSynchronization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('export_type', models.CharField(choices=[('invoices', 'Factures'), ('payments', 'Paiements'), ('clients', 'Clients'), ('products', 'Produits'), ('journal', 'Journal comptable'), ('trial_balance', 'Balance trial')], max_length=50, verbose_name="Type d'export")),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours'), ('completed', 'Complété'), ('failed', 'Échoué')], default='pending', max_length=20, verbose_name='Statut')),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(verbose_name='Date de fin')),
                ('records_count', models.IntegerField(default=0, verbose_name="Nombre d'enregistrements")),
                ('file_path', models.CharField(blank=True, max_length=500, null=True, verbose_name='Chemin fichier')),
                ('file_size', models.BigIntegerField(blank=True, null=True, verbose_name='Taille fichier (bytes)')),
                ('checksum', models.CharField(blank=True, max_length=64, null=True, verbose_name='Checksum SHA256')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name="Message d'erreur")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Complété le')),
                ('created_by', models.CharField(blank=True, max_length=255, null=True, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Synchronisation comptable',
                'verbose_name_plural': 'Synchronisations comptables',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnomalyDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anomaly_type', models.CharField(choices=[('unusual_amount', 'Montant anormal'), ('payment_delay', 'Retard de paiement'), ('duplicate_invoice', 'Facture en doublon'), ('unusual_client', 'Client inhabituel'), ('pricing_error', 'Erreur de tarification'), ('unusual_frequency', 'Fréquence anormale')], max_length=50, verbose_name="Type d'anomalie")),
                ('severity', models.CharField(choices=[('low', 'Basse'), ('medium', 'Moyenne'), ('high', 'Haute'), ('critical', 'Critique')], max_length=20, verbose_name='Sévérité')),
                ('description', models.TextField(verbose_name="Description de l'anomalie")),
                ('detected_value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valeur détectée')),
                ('expected_value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valeur attendue')),
                ('confidence', models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MinValueValidator(100)], verbose_name='Confiance %')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Résolu')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de résolution')),
                ('resolution_notes', models.TextField(blank=True, null=True, verbose_name='Notes de résolution')),
                ('detected_at', models.DateTimeField(auto_now_add=True, verbose_name='Détecté le')),
            ],
            options={
                'verbose_name': "Détection d'anomalie",
                'verbose_name_plural': "Détections d'anomalies",
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='IntelligentAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('anomaly', 'Anomalie détectée'), ('forecast_warning', 'Avertissement prévisions'), ('payment_risk', 'Risque de paiement'), ('revenue_decline', 'Baisse de revenus'), ('unusual_pattern', 'Motif inhabituél'), ('duplicate_detection', 'Doublon détecté')], max_length=50, verbose_name="Type d'alerte")),
                ('priority', models.CharField(choices=[('low', 'Basse'), ('medium', 'Moyenne'), ('high', 'Haute'), ('urgent', 'Urgent')], max_length=20, verbose_name='Priorité')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('recommendation', models.TextField(blank=True, null=True, verbose_name='Recommandation IA')),
                ('is_acknowledged', models.BooleanField(default=False, verbose_name='Confirmé')),
                ('acknowledged_by', models.CharField(blank=True, max_length=255, null=True, verbose_name='Confirmé par')),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True, verbose_name='Confirmé le')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
            ],
            options={
                'verbose_name': 'Alerte intelligente',
                'verbose_name_plural': 'Alertes intelligentes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RevenueForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('weekly', 'Hebdomadaire'), ('monthly', 'Mensuelle'), ('quarterly', 'Trimestrielle'), ('yearly', 'Annuelle')], max_length=20, verbose_name='Période')),
                ('forecast_date', models.DateField(verbose_name='Date de la prévision')),
                ('predicted_revenue', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='CA prédit')),
                ('predicted_invoices', models.IntegerField(verbose_name='Factures prévues')),
                ('confidence_interval_low', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Intervalle bas')),
                ('confidence_interval_high', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Intervalle haut')),
                ('actual_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='CA réel')),
                ('actual_invoices', models.IntegerField(blank=True, null=True, verbose_name='Factures réelles')),
                ('accuracy', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MinValueValidator(100)], verbose_name='Précision %')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Prévision de CA',
                'verbose_name_plural': 'Prévisions de CA',
                'ordering': ['-forecast_date'],
            },
        ),
        migrations.AddIndex(
            model_name='revenueforecast',
            index=models.Index(fields=['period', 'forecast_date'], name='invoice_app_period_05c7c4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='revenueforecast',
            unique_together={('period', 'forecast_date')},
        ),
        migrations.AddField(
            model_name='intelligentalert',
            name='related_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoice_app.client', verbose_name='Client associé'),
        ),
        migrations.AddField(
            model_name='intelligentalert',
            name='related_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoice_app.invoice', verbose_name='Facture associée'),
        ),
        migrations.AddField(
            model_name='anomalydetection',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice_app.invoice', verbose_name='Facture'),
        ),
        migrations.AddIndex(
            model_name='accountingsynchronization',
            index=models.Index(fields=['export_type', 'status'], name='invoice_app_export__e90946_idx'),
        ),
        migrations.AddIndex(
            model_name='accountingsynchronization',
            index=models.Index(fields=['-created_at'], name='invoice_app_created_c71cdb_idx'),
        ),
        migrations.AddIndex(
            model_name='intelligentalert',
            index=models.Index(fields=['priority', 'is_acknowledged'], name='invoice_app_priorit_03e873_idx'),
        ),
        migrations.AddIndex(
            model_name='intelligentalert',
            index=models.Index(fields=['alert_type', '-created_at'], name='invoice_app_alert_t_49553b_idx'),
        ),
        migrations.AddIndex(
            model_name='anomalydetection',
            index=models.Index(fields=['invoice', 'severity'], name='invoice_app_invoice_6ec7f5_idx'),
        ),
        migrations.AddIndex(
            model_name='anomalydetection',
            index=models.Index(fields=['is_resolved', '-detected_at'], name='invoice_app_is_reso_2c1799_idx'),
        ),
        migrations.AddIndex(
            model_name='anomalydetection',
            index=models.Index(fields=['anomaly_type'], name='invoice_app_anomaly_b88afd_idx'),
        ),
    ]
