# Generated by Django 4.2 on 2026-05-12 20:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invoice_app', '0005_accountingsynchronization_anomalydetection_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealtimeNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('anomaly_critical', 'Anomalie Critique'), ('payment_received', 'Paiement Reçu'), ('invoice_overdue', 'Facture en Retard'), ('alert_acknowledged', 'Alerte Reconnue'), ('forecast_updated', 'Prévision Mise à Jour'), ('export_completed', 'Export Complété'), ('system_alert', 'Alerte Système'), ('new_invoice', 'Nouvelle Facture'), ('new_quote', 'Nouveau Devis'), ('payment_reminder', 'Rappel Paiement')], max_length=50, verbose_name='Type')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('message', models.TextField(verbose_name='Message')),
                ('priority', models.CharField(choices=[('low', 'Basse'), ('medium', 'Moyenne'), ('high', 'Élevée'), ('critical', 'Critique')], default='medium', max_length=20, verbose_name='Priorité')),
                ('is_read', models.BooleanField(default=False, verbose_name='Est lu?')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Lu le')),
                ('is_dismissed', models.BooleanField(default=False, verbose_name='Est rejeté?')),
                ('action_url', models.CharField(blank=True, max_length=500, null=True, verbose_name="URL d'action")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expire le')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoice_app.client', verbose_name='Client lié')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoice_app.invoice', verbose_name='Facture liée')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='realtime_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Notification Real-time',
                'verbose_name_plural': 'Notifications Real-time',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdvancedDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Tableau de Bord', max_length=255, verbose_name='Titre')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Activé?')),
                ('widgets_config', models.TextField(default='[]', verbose_name='Configuration des widgets')),
                ('kpi_list', models.TextField(default='[]', verbose_name='Liste des KPIs')),
                ('default_period', models.CharField(choices=[('daily', 'Quotidien'), ('weekly', 'Hebdomadaire'), ('monthly', 'Mensuel'), ('quarterly', 'Trimestriel'), ('yearly', 'Annuel'), ('custom', 'Personnalisé')], default='monthly', max_length=20, verbose_name='Période par défaut')),
                ('color_scheme', models.CharField(default='auto', max_length=50, verbose_name='Schéma de couleur')),
                ('auto_refresh', models.BooleanField(default=True, verbose_name='Rafraîchissement auto?')),
                ('refresh_interval', models.IntegerField(default=300, verbose_name='Intervalle rafraîchissement (secondes)')),
                ('enable_notifications', models.BooleanField(default=True, verbose_name='Notifications activées?')),
                ('notification_thresholds', models.TextField(default='{}', verbose_name='Seuils de notification')),
                ('total_views', models.IntegerField(default=0, verbose_name='Total vues')),
                ('last_accessed', models.DateTimeField(blank=True, null=True, verbose_name='Dernier accès')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='advanced_dashboard', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Tableau de Bord Avancé',
                'verbose_name_plural': 'Tableaux de Bord Avancés',
            },
        ),
        migrations.AddIndex(
            model_name='realtimenotification',
            index=models.Index(fields=['user', '-created_at'], name='invoice_app_user_id_7099ff_idx'),
        ),
        migrations.AddIndex(
            model_name='realtimenotification',
            index=models.Index(fields=['priority', 'is_read'], name='invoice_app_priorit_f4d930_idx'),
        ),
        migrations.AddIndex(
            model_name='realtimenotification',
            index=models.Index(fields=['notification_type'], name='invoice_app_notific_10a6e6_idx'),
        ),
        migrations.AddIndex(
            model_name='advanceddashboard',
            index=models.Index(fields=['user', 'is_enabled'], name='invoice_app_user_id_0d64da_idx'),
        ),
    ]
