# Generated by Django 4.2 on 2026-05-13 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0006_realtimenotification_advanceddashboard_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advanceddashboard',
            name='enable_notifications',
        ),
        migrations.RemoveField(
            model_name='advanceddashboard',
            name='last_accessed',
        ),
        migrations.RemoveField(
            model_name='advanceddashboard',
            name='notification_thresholds',
        ),
        migrations.RemoveField(
            model_name='advanceddashboard',
            name='total_views',
        ),
        migrations.AddField(
            model_name='advanceddashboard',
            name='show_alerts',
            field=models.BooleanField(default=True, verbose_name='Afficher les alertes?'),
        ),
        migrations.AddField(
            model_name='advanceddashboard',
            name='show_anomalies',
            field=models.BooleanField(default=True, verbose_name='Afficher les anomalies?'),
        ),
        migrations.AddField(
            model_name='advanceddashboard',
            name='show_forecasts',
            field=models.BooleanField(default=True, verbose_name='Afficher les prévisions?'),
        ),
        migrations.AlterField(
            model_name='advanceddashboard',
            name='refresh_interval',
            field=models.IntegerField(default=30, verbose_name='Intervalle de rafraîchissement (sec)'),
        ),
    ]
