# Generated by Django 4.2 on 2026-05-13 18:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0007_remove_advanceddashboard_enable_notifications_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='low_stock_threshold',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name="Seuil d'alerte"),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_quantity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock'),
        ),
        migrations.AddField(
            model_name='product',
            name='track_stock',
            field=models.BooleanField(default=True, verbose_name='Suivre le stock'),
        ),
    ]
