# Generated by Django 4.2 on 2026-05-19 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0008_product_low_stock_threshold_product_stock_quantity_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnomalyDetection',
        ),
        migrations.DeleteModel(
            name='RevenueForecast',
        ),
        migrations.DeleteModel(
            name='IntelligentAlert',
        ),
        migrations.DeleteModel(
            name='AccountingSynchronization',
        ),
        migrations.DeleteModel(
            name='RealtimeNotification',
        ),
        migrations.DeleteModel(
            name='AdvancedDashboard',
        ),
    ]
