# Generated by Django 4.2 on 2026-05-19 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0009_delete_ai_models'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['nom'], 'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
        migrations.RemoveField(
            model_name='client',
            name='billing_address',
        ),
        migrations.RemoveField(
            model_name='client',
            name='country',
        ),
        migrations.RemoveField(
            model_name='client',
            name='delivery_address',
        ),
        migrations.RemoveField(
            model_name='client',
            name='name',
        ),
        migrations.RemoveField(
            model_name='client',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='client',
            name='tva_intra',
        ),
        migrations.AddField(
            model_name='client',
            name='adresse_facturation',
            field=models.TextField(default='', verbose_name='Adresse de facturation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='adresse_livraison',
            field=models.TextField(blank=True, null=True, verbose_name='Adresse de livraison'),
        ),
        migrations.AddField(
            model_name='client',
            name='code_postal_facturation',
            field=models.CharField(default='', max_length=10, verbose_name='Code postal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='code_postal_livraison',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Code postal (livraison)'),
        ),
        migrations.AddField(
            model_name='client',
            name='conditions_paiement',
            field=models.CharField(choices=[('IMMEDIAT', 'Paiement immédiat'), ('15_JOURS', '15 jours'), ('30_JOURS', '30 jours')], default='30_JOURS', max_length=20, verbose_name='Conditions de paiement'),
        ),
        migrations.AddField(
            model_name='client',
            name='contact_principal',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Contact principal'),
        ),
        migrations.AddField(
            model_name='client',
            name='livraison_identique_facturation',
            field=models.BooleanField(default=True, verbose_name='Livraison identique à facturation'),
        ),
        migrations.AddField(
            model_name='client',
            name='nom',
            field=models.CharField(default='Sans nom', max_length=255, verbose_name='Nom'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='notes_internes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes internes'),
        ),
        migrations.AddField(
            model_name='client',
            name='numero_tva_intracommunautaire',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Numéro TVA intracommunautaire'),
        ),
        migrations.AddField(
            model_name='client',
            name='pays_facturation',
            field=models.CharField(default='France', max_length=100, verbose_name='Pays'),
        ),
        migrations.AddField(
            model_name='client',
            name='pays_livraison',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Pays (livraison)'),
        ),
        migrations.AddField(
            model_name='client',
            name='raison_sociale',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Raison sociale'),
        ),
        migrations.AddField(
            model_name='client',
            name='siret_siren',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='SIRET/SIREN'),
        ),
        migrations.AddField(
            model_name='client',
            name='statut',
            field=models.CharField(choices=[('ACTIF', 'Actif'), ('INACTIF', 'Inactif')], default='ACTIF', max_length=20, verbose_name='Statut'),
        ),
        migrations.AddField(
            model_name='client',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='type_client',
            field=models.CharField(choices=[('PARTICULIER', 'Particulier'), ('ENTREPRISE', 'Entreprise')], default='PARTICULIER', max_length=20, verbose_name='Type de client'),
        ),
        migrations.AddField(
            model_name='client',
            name='ville_facturation',
            field=models.CharField(default='', max_length=100, verbose_name='Ville'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='ville_livraison',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ville (livraison)'),
        ),
        migrations.AlterField(
            model_name='client',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='client',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Modifié le'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['statut'], name='invoice_app_statut_c9bd00_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['type_client'], name='invoice_app_type_cl_da1809_idx'),
        ),
    ]
