# Generated by Django 4.2 on 2026-05-19 15:44

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0010_alter_client_options_remove_client_billing_address_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name': 'Produit / Service', 'verbose_name_plural': 'Produits / Services'},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='low_stock_threshold',
            new_name='seuil_alerte',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='stock_quantity',
            new_name='stock',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='track_stock',
            new_name='suivre_stock',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='escompte_amount',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='escompte_percentage',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='rabais_amount',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='rabais_percentage',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='remise_amount',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='remise_percentage',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='total',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='total_discount',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='tva_amount',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='price',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='invoice',
            name='remise_globale_montant',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Remise globale €'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='remise_globale_pourcentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Remise globale %'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='sous_total_ht',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Sous-total HT'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='statut',
            field=models.CharField(choices=[('BROUILLON', 'Brouillon'), ('VALIDEE', 'Validée'), ('ENVOYEE', 'Envoyée'), ('PARTIELLEMENT_PAYEE', 'Partiellement payée'), ('PAYEE', 'Payée'), ('EN_RETARD', 'En retard'), ('ANNULEE', 'Annulée')], default='BROUILLON', max_length=30, verbose_name='Statut'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='total_ht',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total HT'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='total_remise',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total remise'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='total_ttc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total TTC'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='total_tva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total TVA'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='prix_unitaire_ht',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix unitaire HT'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='quantite',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='remise_pourcentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Remise %'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='taux_tva',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=5, verbose_name='Taux TVA'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='total_ht',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total HT'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='total_ttc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total TTC'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='total_tva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total TVA'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='unite',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Unité'),
        ),
        migrations.AddField(
            model_name='product',
            name='categorie',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Catégorie'),
        ),
        migrations.AddField(
            model_name='product',
            name='prix_unitaire_ht',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix unitaire HT'),
        ),
        migrations.AddField(
            model_name='product',
            name='statut',
            field=models.CharField(choices=[('ACTIF', 'Actif'), ('INACTIF', 'Inactif')], default='ACTIF', max_length=10, verbose_name='Statut'),
        ),
        migrations.AddField(
            model_name='product',
            name='taux_tva',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=5, verbose_name='Taux TVA'),
        ),
        migrations.AddField(
            model_name='product',
            name='type_item',
            field=models.CharField(choices=[('PRODUIT', 'Produit'), ('SERVICE', 'Service')], default='PRODUIT', max_length=10, verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='product',
            name='unite',
            field=models.CharField(choices=[('PIECE', 'Pièce'), ('HEURE', 'Heure'), ('JOUR', 'Jour'), ('FORFAIT', 'Forfait')], default='PIECE', max_length=10, verbose_name='Unité'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Date de facture'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoice_app.product', verbose_name='Produit / Service'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='product',
            name='reference',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Référence'),
        ),
    ]
