# Generated by Django 4.2 on 2026-05-19 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0012_categorie_produit_and_product_business_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='legal_mentions',
            field=models.TextField(blank=True, null=True, verbose_name='Mentions légales'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes facture'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_terms',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Conditions de paiement'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='stock_movement_done',
            field=models.BooleanField(default=False, verbose_name='Mouvement de stock effectué'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(choices=[('ESPECES', 'Espèces'), ('CARTE_BANCAIRE', 'Carte bancaire'), ('VIREMENT', 'Virement'), ('CHEQUE', 'Chèque'), ('MOBILE_MONEY', 'Mobile Money')], default='VIREMENT', max_length=20, verbose_name='Mode de paiement'),
        ),
    ]
