# Generated by Django 4.2 on 2026-05-20 11:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0013_invoice_legal_mentions_invoice_notes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-date_creation'], 'verbose_name': 'Notification', 'verbose_name_plural': 'Notifications'},
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='invoice_app_client__901700_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='invoice_app_status_e13d0e_idx',
        ),
        migrations.AddField(
            model_name='notification',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date de création'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='lien',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Lien'),
        ),
        migrations.AddField(
            model_name='notification',
            name='lu',
            field=models.BooleanField(default=False, verbose_name='Lu'),
        ),
        migrations.AddField(
            model_name='notification',
            name='niveau',
            field=models.CharField(choices=[('INFO', 'Info'), ('SUCCESS', 'Success'), ('WARNING', 'Warning'), ('ERROR', 'Error')], default='INFO', max_length=20, verbose_name='Niveau'),
        ),
        migrations.AddField(
            model_name='notification',
            name='titre',
            field=models.CharField(default='Notification', max_length=255, verbose_name='Titre'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='type_notification',
            field=models.CharField(choices=[('FACTURE', 'Facture'), ('PAIEMENT', 'Paiement'), ('STOCK', 'Stock'), ('CLIENT', 'Client'), ('SYSTEME', 'Système')], default='SYSTEME', max_length=20, verbose_name='Type de notification'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='invoice_app.client', verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='recipient_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email du destinataire'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(default='pending', max_length=20, verbose_name='Statut legacy'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='subject',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sujet legacy'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Type legacy'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['-date_creation'], name='invoice_app_date_cr_187dfc_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['type_notification', 'niveau'], name='invoice_app_type_no_bd0e0e_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['lu'], name='invoice_app_lu_e32456_idx'),
        ),
    ]
