# Generated by Django 4.2 on 2026-05-20 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0014_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(choices=[('ESPECES', 'Espèces'), ('CARTE_BANCAIRE', 'Carte bancaire'), ('VIREMENT', 'Virement'), ('CHEQUE', 'Chèque'), ('MOBILE_MONEY', 'Mobile Money')], default='VIREMENT', max_length=20, verbose_name='Mode de règlement prévu'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='niveau',
            field=models.CharField(choices=[('HAUTE', 'Haute'), ('MOYENNE', 'Moyenne'), ('BASSE', 'Basse')], default='BASSE', max_length=20, verbose_name='Niveau'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('ESPECES', 'Espèces'), ('CARTE_BANCAIRE', 'Carte bancaire'), ('VIREMENT', 'Virement'), ('CHEQUE', 'Chèque'), ('MOBILE_MONEY', 'Mobile Money')], max_length=20, verbose_name='Méthode de paiement utilisée'),
        ),
    ]
