# Generated by Django 4.2 on 2026-05-20 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0015_payment_method_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='email_sent',
            field=models.BooleanField(default=False, verbose_name='Email envoyé'),
        ),
    ]
