# Generated by Django 4.2 on 2026-05-30 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0016_payment_email_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='currency',
            field=models.CharField(default='EUR', max_length=10, verbose_name='Devise'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='default_legal_mentions',
            field=models.TextField(blank=True, null=True, verbose_name='Mentions légales par défaut'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='default_payment_terms',
            field=models.CharField(blank=True, default='30 jours fin de mois', max_length=255, null=True, verbose_name='Conditions de paiement par défaut'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='default_tva',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=5, verbose_name='TVA par défaut (%)'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='invoice_prefix',
            field=models.CharField(blank=True, default='FAC-', max_length=20, verbose_name='Préfixe facture'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='country',
            field=models.CharField(default='France', max_length=100, verbose_name='Pays'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Adresse email'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='tva_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Numéro TVA intracommunautaire'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Site web'),
        ),
    ]
