# Generated by Django 4.2 on 2026-05-30 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0017_companyinfo_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ville'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Code postal'),
        ),
    ]
